name = "backend"
compatibility_date = "2023-12-01"


[vars]
DATABASE_URL = "postgresql://Posts_owner:w3XPsqR8coVF@ep-mute-dust-a1u1ith5.ap-southeast-1.aws.neon.tech/Vessel?sslmode=require"
JWT_SECRET = "myHkSecret"

